version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/meucarreto_api
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 60
      runas: root 
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 120
      runas: root